---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ikky-3demo-kustom
  namespace: flux-system
spec:
  interval: 10s
  path: ./kustomize_with_kustomize_file # this worked too but should have been;
  prune: true                           # ./kustomize_with_kustomize_file/kustomize
  sourceRef:
    kind: GitRepository
    name: ikky-3demo-source
  targetNamespace: 33-demo
