---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ikky-2demo-kustom
  namespace: flux-system
spec:
  interval: 10s
  path: ./kustomize_without_kustomize_file # this worked too but i think it shoul have been ;
  prune: true                               #./kustomize_without_kustomize_file/manifests
  sourceRef:
    kind: GitRepository
    name: ikky-2demo-source
  targetNamespace: 22-demo
