apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9292
  selector:
    app: notification-controller

