apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"
    persistence:
      enabled: true
      existingClaim: elk-stack-pvc
