apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elk
spec:
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: elk-stack-pvc
    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
    logstashPipeline:
      logstash.conf: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => ["http://elasticsearch-master:9200"]
            index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
          }
        }

