apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 1h0m0s # Check for updates every hour
  url: https://charts.helm.sh/stable
