# flux-cluster/dev-cluster/nginx-ingress-controller-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx  # Name of the Helm release
  namespace: ingress-nginx  # Namespace where the release will be installed
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo  # Reference the unique Helm repository
        namespace: flux-system
  install:
    createNamespace: true  # Create the namespace if it doesn't exist
