apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: default
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins-helm-repo
        namespace: flux-system
      version: 5.4.0
  interval: 1m
  values:
    controller:
      service:
        type: NodePort
      persistence:
        enabled: true
        existingClaim: jenkins-pvc
      replicas: 1  # Set to 1 for the Jenkins master
      jenkinsUrl: http://jenkins:8080  # URL for Jenkins
      kubernetes:
        enabled: true  # Enable Kubernetes plugin
        namespace: default  # Namespace where agents will run
        containerCap: 10  # Maximum number of concurrent agents
        podTemplates:
          - name: jnlp
            label: jnlp
            containers:
              - name: jnlp
                image: jenkins/jnlp-slave:latest  # Image for the Jenkins agent
                args: ['\$(JENKINS_SECRET)', '\$(JENKINS_AGENT_NAME)']
                resource:
                  limits:
                    memory: "2Gi"
                    cpu: "1000m"
                  requests:
                    memory: "1Gi"
                    cpu: "500m"
