#apiVersion: helm.toolkit.fluxcd.io/v2beta1  # Ensure this is the correct version
apiVersion: helm.toolkit.fluxcd.io/v2  # Ensure this is the correct version
kind: HelmRelease
metadata:
  name: jenkins  # This should match the name you want for your HelmRelease
  namespace: default  # Namespace where you want Jenkins to be deployed
spec:
  releaseName: jenkins  # Name of the release in Helm
  chart:
    spec:
      chart: jenkins  # The name of the chart
      sourceRef:
        kind: HelmRepository
        name: jenkins-helm-repo  # Reference the HelmRepository defined above
        namespace: flux-system  # Namespace where the HelmRepository is defined
      version: 3.5.9  # Specify the version of the Jenkins chart you want to install
  interval: 1m  # Required field: How often to reconcile the HelmRelease
  values:
    controller:  # changed from master to controller
      persistence:
        enabled: true
        existingClaim: jenkins-pvc  # Reference to your existing PVC
      replicas: 2  # Set the number of replicas to 2
