apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: nfs-provisioner
      version: 1.0.0 # Specify the correct version of the chart
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  values:
    storageClass:
      name: nfs
      defaultClass: true
    nfs:
      server: nfs-server.example.com # Replace with your actual NFS server address
      path: /nfsexport
